create table products
(
    id           bigint generated by default as identity
        primary key,
    category     varchar(255)
        constraint products_category_check
            check ((category)::text = ANY
                   ((ARRAY ['CAMERA'::character varying, 'ROUTER'::character varying])::text[])),
    company      varchar(255)
        constraint products_company_check
            check ((company)::text = ANY
                   ((ARRAY ['IPTIME'::character varying, 'TPLINK'::character varying, 'NETIS'::character varying, 'MERCUSYS'::character varying, 'ASUS'::character varying, 'MI'::character varying])::text[])),
    created_at   timestamp(6),
    item_id      varchar(255),
    model_code   varchar(255),
    product_id   varchar(255),
    product_name varchar(500),
    updated_at   timestamp(6),
    displayorder integer
);

alter table products
    owner to postgres;

create table favorite_products
(
    id            bigint generated by default as identity
        primary key,
    created_at    timestamp(6),
    display_order integer,
    product_id    bigint
        constraint fk66gqbpuhbuxns99w8sx4ksoke
            references products
);

alter table favorite_products
    owner to postgres;

create table product_daily_data
(
    id               bigint generated by default as identity
        primary key,
    created_at       timestamp(6),
    current_price    varchar(255),
    date             date,
    delivery_method  varchar(255)
        constraint product_daily_data_delivery_method_check
            check ((delivery_method)::text = ANY
                   ((ARRAY ['ROCKET_DELIVERY'::character varying, 'ROCKET_MERCHANT'::character varying, 'NORMAL_DELIVERY'::character varying])::text[])),
    discount_rate    varchar(255),
    display_position integer,
    display_ranking  integer,
    is_ad            boolean,
    original_price   varchar(255),
    product_url      varchar(1000),
    ranking          integer,
    rating           varchar(255),
    review_count     varchar(255),
    product_id       bigint
        constraint fk5c9tx4bt5g1htxov4uldeq1q
            references products
);

alter table product_daily_data
    owner to postgres;
